knnf_whatsup_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: KnnfWhatsupBundle:Default:index }

#INDEX
index:
    pattern: /index/index/
    defaults: { _controller: KnnfWhatsupBundle:Index:index }

user_index:
    pattern: /user/index/
    defaults: { _controller: KnnfWhatsupBundle:User:index }

user_add:
    pattern: /user/add/
    defaults: { _controller: KnnfWhatsupBundle:User:add }

user_delete:
    pattern: /user/delete/
    defaults: { _controller: KnnfWhatsupBundle:User:delete }

#ARTICLE
article_index:
    pattern: /article/index/
    defaults: { _controller: KnnfWhatsupBundle:Article:index }

article_add:
    pattern: /article/add/
    defaults: { _controller: KnnfWhatsupBundle:Article:add }

article_edit:
    pattern: /article/edit/
    defaults: { _controller: KnnfWhatsupBundle:Article:edit }

article_delete:
    pattern: /article/delete/
    defaults: { _controller: KnnfWhatsupBundle:Article:delete }

article_activate:
    pattern: /article/activate/
    defaults: { _controller: KnnfWhatsupBundle:Article:activate }

#CATEGORY
category_index:
    pattern: /category/index/
    defaults: { _controller: KnnfWhatsupBundle:Category:index }

category_add:
    pattern: /category/add/
    defaults: { _controller: KnnfWhatsupBundle:Category:add }

category_edit:
    pattern: /category/edit/
    defaults: { _controller: KnnfWhatsupBundle:Category:edit }

category_delete:
    pattern: /category/delete/
    defaults: { _controller: KnnfWhatsupBundle:Category:delete }

category_activate:
    pattern: /category/activate/
    defaults: { _controller: KnnfWhatsupBundle:Category:activate }

#EVENT
event_index:
    pattern: /event/index
    defaults: { _controller: KnnfWhatsupBundle:Event:index }

event_add:
    pattern: /event/add/
    defaults: { _controller: KnnfWhatsupBundle:Event:add }

event_edit:
    pattern: /event/edit/
    defaults: { _controller: KnnfWhatsupBundle:Event:edit }

event_delete:
    pattern: /event/delete/
    defaults: { _controller: KnnfWhatsupBundle:Event:delete }

event_activate:
    pattern: /event/activate/
    defaults: { _controller: KnnfWhatsupBundle:Event:activate }
