parameters:
#    knnf_whatsup.example.class: Knnf\WhatsupBundle\Example

services:
#    knnf_whatsup.example:
#        class: %knnf_whatsup.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
