parameters:
#    knnf_whatsup.example.class: Knnf\WhatsupBundle\Example

services:
#    knnf_whatsup.example:
#        class: Knnf\WhatsupBundle\Controller\UserController
#        arguments: [@doctrine.orm.default_entity_manager]
